2024/11/18 10:51:42 [error] 29#29: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 134.17.170.54, server: , request: "GET /favicon.ico HTTP/1.1", host: "194.87.201.198", referrer: "http://194.87.201.198/"
2024/11/18 11:38:52 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 11:38:52 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 11:38:53 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "194.87.201.198"
2024/11/18 11:38:54 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "194.87.201.198"
2024/11/18 11:39:06 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 11:39:06 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 11:39:10 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "194.87.201.198"
2024/11/18 11:51:41 [error] 29#29: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 95.214.55.79, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 11:51:41 [error] 29#29: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 95.214.55.79, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 11:52:55 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 95.214.53.91, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 11:52:55 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 95.214.53.91, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 11:58:49 [error] 29#29: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 46.19.138.234, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 11:58:49 [error] 29#29: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 46.19.138.234, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 12:02:46 [error] 29#29: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 71.6.232.20, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 12:02:46 [error] 29#29: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 71.6.232.20, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 12:14:14 [error] 29#29: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 216.218.206.69, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 12:14:14 [error] 29#29: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 216.218.206.69, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 12:16:22 [error] 29#29: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 216.218.206.69, server: , request: "GET /webui/ HTTP/1.1", upstream: "http://127.0.0.1:5601/webui/", host: "194.87.201.198"
2024/11/18 12:16:22 [error] 29#29: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 216.218.206.69, server: , request: "GET /webui/ HTTP/1.1", upstream: "http://127.0.0.1:5601/webui/", host: "194.87.201.198"
2024/11/18 12:17:22 [error] 29#29: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 216.218.206.69, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5601/favicon.ico", host: "194.87.201.198"
2024/11/18 12:17:22 [error] 29#29: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 216.218.206.69, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5601/favicon.ico", host: "194.87.201.198"
2024/11/18 12:18:15 [error] 29#29: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 216.218.206.69, server: , request: "GET /geoserver/web/ HTTP/1.1", upstream: "http://127.0.0.1:5601/geoserver/web/", host: "194.87.201.198"
2024/11/18 12:18:15 [error] 29#29: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 216.218.206.69, server: , request: "GET /geoserver/web/ HTTP/1.1", upstream: "http://127.0.0.1:5601/geoserver/web/", host: "194.87.201.198"
2024/11/18 12:33:35 [error] 29#29: *32 connect() failed (111: Connection refused) while connecting to upstream, client: 120.85.112.192, server: , request: "POST /GponForm/diag_Form?images/ HTTP/1.1", upstream: "http://127.0.0.1:5601/GponForm/diag_Form?images/", host: "127.0.0.1:80"
2024/11/18 12:33:35 [error] 29#29: *32 connect() failed (111: Connection refused) while connecting to upstream, client: 120.85.112.192, server: , request: "POST /GponForm/diag_Form?images/ HTTP/1.1", upstream: "http://127.0.0.1:5601/GponForm/diag_Form?images/", host: "127.0.0.1:80"
2024/11/18 12:43:32 [error] 29#29: *36 connect() failed (111: Connection refused) while connecting to upstream, client: 167.94.138.160, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198:80"
2024/11/18 12:43:32 [error] 29#29: *36 connect() failed (111: Connection refused) while connecting to upstream, client: 167.94.138.160, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198:80"
2024/11/18 12:43:43 [error] 29#29: *39 connect() failed (111: Connection refused) while connecting to upstream, client: 167.94.138.160, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 12:43:43 [error] 29#29: *39 connect() failed (111: Connection refused) while connecting to upstream, client: 167.94.138.160, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5601/", host: "194.87.201.198"
2024/11/18 12:49:59 [emerg] 1#1: host not found in upstream "kibana" in /etc/nginx/nginx.conf:19
2024/11/18 12:52:32 [emerg] 1#1: host not found in upstream "kibana" in /etc/nginx/nginx.conf:19
2024/11/18 14:02:00 [emerg] 1#1: host not found in upstream "kibana" in /etc/nginx/nginx.conf:19
2024/11/18 14:05:00 [emerg] 1#1: unknown directive "Ð»worker_processes" in /etc/nginx/nginx.conf:1
2024/11/18 14:05:55 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.5:5601/", host: "194.87.201.198"
2024/11/18 14:05:56 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.5:5601/", host: "194.87.201.198"
2024/11/18 14:05:57 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.5:5601/", host: "194.87.201.198"
2024/11/18 15:36:36 [emerg] 1#1: host not found in upstream "kibana" in /etc/nginx/nginx.conf:19
2024/11/18 15:40:37 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:5601/", host: "194.87.201.198"
2024/11/18 15:40:45 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:5601/", host: "194.87.201.198"
2024/11/18 15:40:50 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:5601/", host: "194.87.201.198"
2024/11/18 15:40:51 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:5601/", host: "194.87.201.198"
2024/11/18 15:41:04 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:5601/", host: "194.87.201.198"
2024/11/18 15:41:06 [error] 29#29: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 141.98.11.175, server: , request: "POST /cgi-bin/hotspotlogin.cgi HTTP/1.1", upstream: "http://172.18.0.4:5601/cgi-bin/hotspotlogin.cgi", host: "194.87.201.198:80"
2024/11/18 22:20:45 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 134.17.170.54, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:5601/", host: "194.87.201.198"
